from __future__ import annotations

from .models import Movie

MOVIES: tuple[Movie, ...] = (
    Movie(
        title="The Princess Bride",
        year=1987,
        runtime_minutes=98,
        genres=("fantasy", "adventure", "romance", "comedy"),
        mood_tags=("funny", "uplifting", "adventurous", "cozy"),
        family_friendly=True,
        synopsis="A playful fairy-tale adventure with sword fights, romance, and dry humor.",
    ),
    Movie(
        title="Paddington 2",
        year=2017,
        runtime_minutes=103,
        genres=("family", "comedy", "adventure"),
        mood_tags=("uplifting", "funny", "cozy"),
        family_friendly=True,
        synopsis="A warm and funny family movie about kindness, community, and marmalade.",
    ),
    Movie(
        title="Spider-Man: Into the Spider-Verse",
        year=2018,
        runtime_minutes=117,
        genres=("animation", "action", "adventure", "sci-fi"),
        mood_tags=("adventurous", "funny", "inspiring"),
        family_friendly=True,
        synopsis="A kinetic animated superhero story with style and heart.",
    ),
    Movie(
        title="Coco",
        year=2017,
        runtime_minutes=105,
        genres=("animation", "family", "fantasy"),
        mood_tags=("uplifting", "cozy", "emotional", "inspiring"),
        family_friendly=True,
        synopsis="A vibrant family story centered on memory, music, and heritage.",
    ),
    Movie(
        title="The Martian",
        year=2015,
        runtime_minutes=144,
        genres=("sci-fi", "adventure", "drama"),
        mood_tags=("inspiring", "tense", "adventurous"),
        family_friendly=False,
        synopsis="A stranded astronaut uses science and grit to survive on Mars.",
    ),
    Movie(
        title="Arrival",
        year=2016,
        runtime_minutes=116,
        genres=("sci-fi", "drama"),
        mood_tags=("mind_bending", "thoughtful", "emotional"),
        family_friendly=False,
        synopsis="A linguist works to communicate with alien visitors and confronts time itself.",
    ),
    Movie(
        title="Inception",
        year=2010,
        runtime_minutes=148,
        genres=("sci-fi", "action", "thriller"),
        mood_tags=("mind_bending", "tense", "epic"),
        family_friendly=False,
        synopsis="A layered heist inside dreams pushes reality to the breaking point.",
    ),
    Movie(
        title="Interstellar",
        year=2014,
        runtime_minutes=169,
        genres=("sci-fi", "adventure", "drama"),
        mood_tags=("epic", "emotional", "mind_bending"),
        family_friendly=False,
        synopsis="An astronaut crew seeks a new home for humanity beyond a wormhole.",
    ),
    Movie(
        title="The Matrix",
        year=1999,
        runtime_minutes=136,
        genres=("sci-fi", "action"),
        mood_tags=("mind_bending", "dark", "adventurous"),
        family_friendly=False,
        synopsis="A hacker discovers his world is a simulation and joins a rebellion.",
    ),
    Movie(
        title="Knives Out",
        year=2019,
        runtime_minutes=130,
        genres=("mystery", "comedy", "crime"),
        mood_tags=("funny", "tense", "cozy"),
        family_friendly=False,
        synopsis="A detective investigates a wealthy family's tangled secrets.",
    ),
    Movie(
        title="Mad Max: Fury Road",
        year=2015,
        runtime_minutes=120,
        genres=("action", "adventure"),
        mood_tags=("adventurous", "tense", "epic"),
        family_friendly=False,
        synopsis="A relentless desert chase that redefines action filmmaking.",
    ),
    Movie(
        title="La La Land",
        year=2016,
        runtime_minutes=128,
        genres=("romance", "drama", "musical"),
        mood_tags=("romantic", "emotional", "uplifting"),
        family_friendly=False,
        synopsis="A modern musical romance about ambition, love, and compromise.",
    ),
    Movie(
        title="Little Women",
        year=2019,
        runtime_minutes=135,
        genres=("drama", "romance"),
        mood_tags=("cozy", "emotional", "inspiring"),
        family_friendly=True,
        synopsis="A lively adaptation of family, art, and independence.",
    ),
    Movie(
        title="The Dark Knight",
        year=2008,
        runtime_minutes=152,
        genres=("action", "crime", "drama"),
        mood_tags=("dark", "tense", "epic"),
        family_friendly=False,
        synopsis="Batman faces chaos embodied in the Joker.",
    ),
    Movie(
        title="Your Name",
        year=2016,
        runtime_minutes=106,
        genres=("animation", "romance", "fantasy", "drama"),
        mood_tags=("romantic", "mind_bending", "emotional"),
        family_friendly=True,
        synopsis="Two teenagers mysteriously swap lives and chase a shared destiny.",
    ),
    Movie(
        title="Everything Everywhere All at Once",
        year=2022,
        runtime_minutes=139,
        genres=("sci-fi", "action", "comedy", "drama"),
        mood_tags=("mind_bending", "funny", "emotional", "adventurous"),
        family_friendly=False,
        synopsis="A multiverse adventure about family, identity, and improbable heroism.",
    ),
    Movie(
        title="Dune",
        year=2021,
        runtime_minutes=155,
        genres=("sci-fi", "adventure", "drama"),
        mood_tags=("epic", "dark", "thoughtful"),
        family_friendly=False,
        synopsis="A young heir confronts power, prophecy, and survival on Arrakis.",
    ),
    Movie(
        title="The Grand Budapest Hotel",
        year=2014,
        runtime_minutes=99,
        genres=("comedy", "crime", "adventure"),
        mood_tags=("funny", "cozy", "adventurous"),
        family_friendly=False,
        synopsis="A whimsical caper through a fading European hotel.",
    ),
    Movie(
        title="Hidden Figures",
        year=2016,
        runtime_minutes=127,
        genres=("drama", "history"),
        mood_tags=("inspiring", "uplifting", "thoughtful"),
        family_friendly=True,
        synopsis="Three brilliant mathematicians help power the U.S. space race.",
    ),
    Movie(
        title="Sing Street",
        year=2016,
        runtime_minutes=106,
        genres=("comedy", "drama", "music"),
        mood_tags=("uplifting", "funny", "romantic"),
        family_friendly=True,
        synopsis="A teenager starts a band to escape his rough school life.",
    ),
    Movie(
        title="The Secret Life of Walter Mitty",
        year=2013,
        runtime_minutes=114,
        genres=("adventure", "comedy", "drama"),
        mood_tags=("uplifting", "adventurous", "inspiring"),
        family_friendly=True,
        synopsis="A daydreamer embarks on a real-world journey that changes his life.",
    ),
)
